### ISSUE TITLE
Options in russian

### ISSUE THREAD

**Issue by Culetto** [RadMuravTeam/Fallout-Sonora-ENG#100]
![image](https://github.com/RadMuravTeam/Fallout-Sonora-ENG/assets/88935956/9e46822d-0423-42c2-ba8c-91f13428530c)
![image](https://github.com/RadMuravTeam/Fallout-Sonora-ENG/assets/88935956/1cc31db3-2dbd-4274-917b-c58a57b1eaa8)

**Comment by FicMon** [comment]
Working on it.

**Comment by FicMon** [comment]
Fixed. Will be included in next release in about 3 hours.
