### ISSUE TITLE
should be strong punch instead of force punch

### ISSUE THREAD

**Issue by Culetto** [RadMuravTeam/Fallout-Sonora-ENG#108]
![image](https://github.com/RadMuravTeam/Fallout-Sonora-ENG/assets/88935956/dd4588aa-1af3-48ff-ac59-4b9ebc2eb7a6)

**Comment by FicMon** [comment]
The feedback is appreciated, will get to it.

**Comment by FicMon** [comment]
![slika_2024-01-27_171056551](https://github.com/RadMuravTeam/Fallout-Sonora-ENG/assets/52656587/4003e12f-985e-4e92-ae81-f05d8ae70b11)
Fixed
