### ISSUE TITLE
Cant copy files into fallout Sonora directory (master.dat +dayglow_dlc.dat)

### ISSUE THREAD

**Issue by grayfoxx85** [RadMuravTeam/Fallout-Sonora-ENG#109]
After installing fallout sonora extended version i am tring to copy translation 1.7 zip files to sonora directory but it wont allow me to do it.
i tried to make directory not read only.

Tried several methots but couldnt make it.

İ really hope to see a solution.

**Comment by FicMon** [comment]
Have you even read the readme file? Download from the releases on the right side of the screen. If you want the newest files, you'll have to wait a bit until we at least add cutscenes in English. It's either going to take one week or a few months for that to happen.

**Comment by FicMon** [comment]
Right now there's nothing groundbreaking in 1.7 anyways. A bit of fixes in general to the translation and translated 4 interface screens to English (doesn't impede your ability to play in 1.6).
